### ISSUE TITLE
SIGSEGV (Address boundary error)  on node 12 and 11

### ISSUE THREAD

**Issue by wanderer** [websockets/bufferutil#1]
Im getting SIGSEGV (Address boundary error)  when using `mask` on node 12 and 11

**Comment by LostInBrittany** [comment]
I confirmed it's an issue, at least on an Ubuntu (14.10) using GCC 4.9. 
Maybe the given  [changes to the 0.12 Buffer API] (https://github.com/joyent/node/wiki/Api-changes-between-v0.10-and-v0.12#buffers) have broken something?
In the state, it's broken and it breaks other modules using it, as [websockets](https://github.com/websockets/).  If you have a moment, could you please look at it? THANKS in advance!

**Comment by 3rd-Eden** [comment]
Master have been upgraded with a new version nan, that might resolve some of the build issues you're seeing. Re-open if this issue still happens with the latest release (1.2.0)

**Comment by Nibbler999** [comment]
Still happens with the latest release. Debug builds don't crash - it only happens when compiled -O3 (-O2 works fine as a workaround).
