### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by umeshblader3** [websockets/bufferutil#106]
When i build angular universal, I get this error. Please help me.
/node_modules/node-gyp-build/index.js
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/bufferutil/index.js
 @ ./node_modules/ws/lib/buffer-util.js
 @ ./node_modules/ws/lib/receiver.js
 @ ./node_modules/ws/index.js
 @ ./server.ts

**Comment by lpinca** [comment]
From https://github.com/websockets/ws#ws-a-nodejs-websocket-library

> Note: This module does not work in the browser. The client in the docs is a reference to a back end with the role of a client in the WebSocket communication. Browser clients must use the native WebSocket object. To make the same code work seamlessly on Node.js and the browser, you can use one of the many wrappers available on npm, like isomorphic-ws.

**Comment by lpinca** [comment]
Closing as answered. Discussion can continue if needed.
