### ISSUE TITLE
Segmentation fault: 11 with node v4.0.0-rc.5

### ISSUE THREAD

**Issue by kylepaulsen** [websockets/bufferutil#13]
It's me again...

Same story with this one:

So I noticed this when trying to use the ws module. The fallback files don't get a chance to run because node just seg faults. I assume there is some NAN magic that needs to be upgraded or something? rvagg mentions it in the third paragraph of the first post in nodejs/node#2522 . It would be awesome to get this working for node 4 soon :)

In the meantime, it seems like the fallback files work if I change the source to not even try to require the native versions. So doing that for now.

**Comment by bassettsj** [comment]
Having the same issues here. :smile:

**Comment by 3rd-Eden** [comment]
Closing this issue, you probably forgot to do a npm rebuild or npm install after switching node versions causing binary addons to be linked against old v8 binaries instead of the new and shiny one's
