### ISSUE TITLE
Localstack integration

### ISSUE THREAD

**Issue by MichaelMcKavanagh** [websockets/bufferutil#130]
localstack    | WARNING: An illegal reflective access operation has occurred
localstack    | WARNING: Illegal reflective access by org.eclipse.jetty.util.BufferUtil (file:/opt/code/localstack/localstack/infra/stepfunctions/jetty-util-9.3.x.jar) to field java.nio.MappedByteBuffer.fd
localstack    | WARNING: Please consider reporting this to the maintainers of org.eclipse.jetty.util.BufferUtil

**Comment by lpinca** [comment]
You are posting this in the wrong repository. This is a module for Node.js. [`org.eclipse.jetty.util.BufferUtil`](https://www.eclipse.org/jetty/javadoc/9.4.11.v20180605/org/eclipse/jetty/util/BufferUtil.html) is a completely unrelated Java  package.
