### ISSUE TITLE
Deploy binaries for ARM

### ISSUE THREAD

**Issue by BHSPitMonkey** [websockets/bufferutil#131]
It would be great if Travis also cross-compiled binaries for `armv7l` and other ARM architectures, since on some of these kinds of platforms/distributions it can be a bit of work to get a compiler toolchain up and running. `prebuildify` supports this, but right now it looks like we're only targeting the CI machine's own architecture (the default option).

Thanks for maintaining this library!

**Comment by lpinca** [comment]
It is not clear to me how to use `prebuildify` to produce cross-compiled binaries. I tried with

```
prebuildify --arch arm --armv 6 --napi --platform linux --tag-armv
```

but the binary does not work on `armv6l`.

I noticed that [`leveldown`](https://github.com/Level/leveldown) uses [`prebuildify-cross`](https://github.com/prebuild/prebuildify-cross) to build binaries for ARM.

Travis CI supports [`arm64`](https://docs.travis-ci.com/user/multi-cpu-architectures/) so adding that should be easy.

Do you know how to cross-compile for ARM using only `prebuildify`?

**Comment by BHSPitMonkey** [comment]
I do not 😕 But at first glance, `prebuildify-cross` does look like it would reduce the necessary amount of fussing over getting all the cross-compilation toolchains set up on the build box.

**Comment by chenrui333** [comment]
Hi @lpinca, did this commit 790c14776b0233b7ff4e87c4b576477c7f5f0261 get added anywhere? I did not see that commit part of any branch? Thanks!

**Comment by lpinca** [comment]
It was force pushed as https://github.com/websockets/bufferutil/commit/82bd20a9fba9e2742d53353b7467160d48a771e3.
