### ISSUE TITLE
"node-gyp-build" issue

### ISSUE THREAD

**Issue by Sunilkaisolagi** [websockets/bufferutil#133]
I am seeing the script "node-gyp-build" failing(Probably with the release of 4.0.3) 
I use Node 4.4.2.
here is the console log.
![image](https://user-images.githubusercontent.com/46446963/104725224-c8f1e780-5757-11eb-8123-90c668a939e3.png)

Any help here?

**Comment by lpinca** [comment]
Can please provide more informations? Can you add more log lines? What is the OS? It should not be an issue with `node-gyp-build` as it was not updated between version `4.0.2` and `4.0.3`.

**Comment by Sunilkaisolagi** [comment]
Windows 10.
Node 4.4.2

It used to work before this update.

**Comment by lpinca** [comment]
Does it work if you install version `4.0.2` (`npm install bufferutil@4.0.2`)?

**Comment by lpinca** [comment]
I'm closing this because with Nodejs v4.x and npm v2.x the installation fails with all `bufferutil` v4.x versions.
Also, `bufferutil@4` uses [N-API](https://nodejs.org/api/n-api.html#n_api_n_api) so the native module will only work on Node.js >= v6.14.2.
