### ISSUE TITLE
Deploy binaries for Apple Silicon

### ISSUE THREAD

**Issue by chenrui333** [websockets/bufferutil#135]
It looks like whatever change which fixes #131 did not include the prebuilt binary for apple silicon (aarm64). Let me know if I missed anything, thanks!

**Comment by lpinca** [comment]
Correct, a prebuilt binary for Apple silicon is not included. There is one for ARM64 but for Linux. I'm not sure if there is an easy way to cross compile for Apple silicon in GitHub Actions.

**Comment by lpinca** [comment]
I think we should wait for https://github.com/actions/virtual-environments/issues/2187.

**Comment by lpinca** [comment]
As suggested in https://github.com/prebuild/prebuildify/issues/52 we could use build a universal binary as done by [`fsevents`](https://github.com/fsevents/fsevents/pull/350) but this is blocked by https://github.com/prebuild/prebuildify/issues/52.

**Comment by chenrui333** [comment]
I think a universal binary would be a much better approach, we can simplify the homebrew audit check (as we did for fsevents)
