### ISSUE TITLE
Bus error since 4.0.4 on a Raspberry Pi

### ISSUE THREAD

**Issue by merdok** [websockets/bufferutil#137]
Hi,

the recent update (4.0.4) is causing my nodejs app to crash, i am using https://www.npmjs.com/package/websocket as a dependency to connect to a websocket endpoint, which has this package as dependency.
I was tracking down the issue and found out that the "Bus error" happens during the `mask` function here https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketFrame.js#L265

```
source = <Buffer 7b 22 69 64 22 3a 22 62 61 63 30 33 38 30 36 30 30 30 31 22 2c 22 74 79 70 65 22 3a 22 72 65 71 75 65 73 74 22 2c 22 75 72 69 22 3a 22 73 73 61 70 3a ... 37 more bytes>
mask = <Buffer 48 29 6e 2b>
output = <Buffer 81 d7 48 29 6e 2b 00 00 08 94 21 02 01 00 00 00 88 0f 00 00 2c 00 00 00 88 90 21 02 68 ad 21 02 73 65 74 4e 6f 44 65 6c 61 79 21 02 00 00 00 00 94 3d ... 43 more bytes>
offset = 6
length =87
```

I have no idea what you changed in version 4.0.4 but when i rollback to version 4.0.3 then it still works. 
As far as I understand that some build c program is called to execute those functions faster but apparently it is now broken on some machines. I am running on a Raspberry Pi:
`Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux`

Can you tell me what the issue here is, and how to fix this? Can it be that the latest update broke this package for raspberry pi devices?

**Comment by lpinca** [comment]
We rebuilt the binary but that is automated and we made no changes. Maybe the compiler used in https://github.com/dockcross/dockcross/tree/master/linux-armv7 was updated and it produced a different binary.

Can you try to run this script https://github.com/websockets/bufferutil/blob/v4.0.4/package.json#L13, copy the generated binary to your Raspberry Pi and see if it works?

This issue might be similar to https://github.com/websockets/bufferutil/issues/132.

**Comment by merdok** [comment]
I have tried that and the issue is still there. 
But i am pretty certain that something is broken with the binary after your recent update To be sure about that the binary has an issue, I renamed the `node.napi.armv7.node` on my Raspberry Pi to some random name `blabla.node`, and the `Bus error` is gone and everything works again. I guess when the correct binary cannot be found then it defaults to `fallback.js`, right?

Maybe something with the docker container changed since you automatically build the binary last time?

**Comment by merdok** [comment]
That would be fine with me, but you could also revert back to the binaries from 4.0.3

**Comment by lpinca** [comment]
> That would be fine with me, but you could also revert back to the binaries from 4.0.3

Then the next time we cut a new release the binaries will be broken again.

**Comment by lpinca** [comment]
According to https://stackoverflow.com/questions/212466/what-is-a-bus-error-is-it-different-from-a-segmentation-fault it is a memory alignment issue and if I have to guess, it was caused by https://github.com/dockcross/dockcross/commit/7b63720438b7a4ac3aed32672546162e61115335#diff-f9e3abded6708e2d856adcdaeb77508db9fb89eb724ac8d330cfcac014a5dab0.

**Comment by UncleSamSwiss** [comment]
BTW: GitHub Actions allows you to run builds directly on ARM. I have never done this, but I would expect that you can (simply) add it to your execution matrix and then gather the binary during the release.

**Comment by Apollon77** [comment]
It is verifed that deleting the binary fixes the issue. Tries to do a local rebuild or such were not really changeing anything ... so we need a new release of both... thank you for your support here

**Comment by Lyxal12** [comment]
Sorry for the question, but i am new to linux/raspberry.

How do i replace the binary?

**Comment by lpinca** [comment]
@Lyxal12 if you install the latest version (4.0.5) you don't have to replace anything.
