### ISSUE TITLE
node-gyp build failed macos (node 16.3.0 and 17.2.0)

### ISSUE THREAD

**Issue by GreenAsJade** [websockets/bufferutil#141]
mgregory@MacBook-Pro ogs % node -v
v16.3.0

mgregory@MacBook-Pro ogs % gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

mgregory@MacBook-Pro ogs % yarn
yarn install v1.22.15
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning socket.io > socket.io-parser > json3@3.3.2: Please use the native JSON object instead of JSON 3
warning socket.io > socket.io-adapter > socket.io-parser > json3@3.2.6: Please use the native JSON object instead of JSON 3
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
error /Users/mgregory/Documents/ogs/ogs/node_modules/bufferutil: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/mgregory/Documents/ogs/ogs/node_modules/bufferutil
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.3.0 | darwin | x64
gyp info find Python using Python version 3.9.7 found at "/Users/mgregory/.pyenv/versions/3.9.7/bin/python3"
gyp info spawn /Users/mgregory/.pyenv/versions/3.9.7/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/mgregory/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mgregory/Documents/ogs/ogs/node_modules/bufferutil/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mgregory/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/mgregory/Library/Caches/node-gyp/16.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/mgregory/Library/Caches/node-gyp/16.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/mgregory/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/mgregory/Library/Caches/node-gyp/16.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/mgregory/Documents/ogs/ogs/node_modules/bufferutil',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.cc:25:30: error: no template named 'Handle' in namespace 'v8'
  static void Initialize(v8::Handle<v8::Object> target)
                         ~~~~^

[ 20 more ]

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mgregory/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/mgregory/.nvm/versions/node/v16.3.0/bin/node" "/Users/mgregory/.nvm/versions/node/v16.3.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mgregory/Documents/ogs/ogs/node_modules/bufferutil
gyp ERR! node -v v16.3.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
mgregory@MacBook-Pro ogs % 


Same problem with node 17.2.0

**Comment by lpinca** [comment]
What is the bufferutil version? I think you are using an outdated version.

**Comment by GreenAsJade** [comment]
The package.json just says "bufferutil", so I presume it is trying to pull and build the latest?

  "dependencies": {
    "body-parser": "^1.15.2",
    "cassandra-driver": "=3.x.x",
    "deep-diff": "=0.3.x",
    "express": "^4.14.0",
    "influx": "^5.0.0-alpha.4",
    "jsonwebtoken": "=5.7.x",
    "lodash": "=4.13.1",
    "logstash-client": "=1.1.1",
    "lokijs": "=1.3.16",
    "node-gyp": ">1.0.0",
    "object-hash": ">=1.1.x",
    "promise-queue": "=2.2.3",
    "redis": "=0.10.x",
    "socket.io": "=1.5.1",
    "socket.io-client": "=1.5.1",
    "tracer": "=0.8.x"
  },
  "bundledDependencies": [
    "socket.io",
    "socket.io-client",
    "express",
    "body-parser",
    "redis",
    "cassandra-driver",
    "object-hash",
    "deep-diff",
    "jsonwebtoken",
    "tracer",
    "lokijs",
    "promise-queue",
    "lodash",
    "node-gyp",
    "bufferutil"
  ],

**Comment by lpinca** [comment]
[`bundledDependencies`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#bundleddependencies) is a different thing. I guess you are using it as an indirect dependency. Try to run `yarn list --pattern bufferutil` to find out the version.

**Comment by GreenAsJade** [comment]
Thanks for your fast help - you are right (of course) an old version was being specified.
