### ISSUE TITLE
TypeError: bufferUtil.mask is not a function

### ISSUE THREAD

**Issue by tavro** [websockets/bufferutil#146]
**Info**
OS: Ubuntu
Node version: 8.9.3
NPM version: 5.5.1

**Error**
/app/node_modules/browser-sync/node_modules/ws/lib/buffer-util.js:115
      else bufferUtil.unmask(buffer, mask);
                      ^
TypeError: bufferUtil.unmask is not a function
    at unmask (/app/node_modules/browser-sync/node_modules/ws/lib/buffer-util.js:115:23)
[...]

**Additional info**
Running in a docker container.
Added to a project based on open source project openstf/stf, so the dependencies looks alike.

**Comment by lpinca** [comment]
The error is thrown by https://github.com/websockets/ws/blob/4b62fbf945cee92f0b06535d8249b0a1d5037cea/lib/buffer-util.js#L115 and it does not make much sense. See this discussion https://github.com/websockets/ws/issues/2057.

**Comment by lpinca** [comment]
I'm closing this as answered.
