### ISSUE TITLE
Linux arm64 binaries

### ISSUE THREAD

**Issue by tbondarchuk** [websockets/bufferutil#150]
Any chances of adding cross-compiling linux arm64 binaries to github actions? They were produced while ci was hosted on travis.

**Comment by lpinca** [comment]
See https://github.com/websockets/bufferutil/commit/42c6780094bdd093199587e2456814a405a06c6e.

**Comment by tbondarchuk** [comment]
@lpinca damn.. so, just to confirm if I got this correctly: cross-compiled arm binary does not work on arm anyway, and even if compile it on arm it still probably won't work on every arm processor and the best way is simply to compile it right where you'll be using it?

**Comment by lpinca** [comment]
Yes, that is the gist of it. Most of the issues started with the glibc update in https://github.com/dockcross/dockcross/commit/7b63720438b7a4ac3aed32672546162e61115335#diff-f9e3abded6708e2d856adcdaeb77508db9fb89eb724ac8d330cfcac014a5dab0.
