### ISSUE TITLE
Problem installing on OS X 10.10.5

### ISSUE THREAD

**Issue by bob-martin** [websockets/bufferutil#17]
sudo npm install -g bufferutil

> bufferutil@1.2.1 install /usr/local/lib/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bufferutil"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

**Comment by venoma333** [comment]
Chming in here. Same issue on Arch Linux with nodejs-4.1.0

Logs:
```
8381 verbose stack Error: bufferutil@1.1.0 install: `node-gyp rebuild`
8381 verbose stack Exit status 1
8381 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
8381 verbose stack     at emitTwo (events.js:87:13)
8381 verbose stack     at EventEmitter.emit (events.js:172:7)
8381 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
8381 verbose stack     at emitTwo (events.js:87:13)
8381 verbose stack     at ChildProcess.emit (events.js:172:7)
8381 verbose stack     at maybeClose (internal/child_process.js:817:16)
8381 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
8382 verbose pkgid bufferutil@1.1.0
8383 verbose cwd /home/ted/Projects/bemoir-front-end
8384 error Linux 4.1.6-1-ARCH
8385 error argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "webpack-dev-server"
8386 error node v4.1.0
8387 error npm  v3.3.3
8388 error code ELIFECYCLE
8389 error bufferutil@1.1.0 install: `node-gyp rebuild`
8389 error Exit status 1
8390 error Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
8390 error This is most likely a problem with the bufferutil package,
8390 error not with npm itself.
8390 error Tell the author that this fails on your system:
8390 error     node-gyp rebuild
8390 error You can get their info via:
8390 error     npm owner ls bufferutil
8390 error There is likely additional logging output above.
8391 verbose exit [ 1, true ]
```

**Comment by StrikeForceZero** [comment]
@venoma333 I'm going to suspect you have a nested dependency requiring an older version of bufferutil. 

Note: ```bufferutil@1.1.0``` current version is 1.2.1

If you find the offending package you can shrink wrap it creating a npm-shrinkwrap.json file and then adding the tree all the way down...

for example gulp-protractor requires protractor which requires an older version of selenium-webdriver which requires an older version of ws which requires an older version of bufferutils... lol

```{
  "name": "gulp-protractor",
  "version": "^1.0.0",
  "dependencies": {
    "protractor": {
      "version": "^2.0.0",
      "from": "protractor@^1.0.0",
      "dependencies": {
        "selenium-webdriver": {
          "version": "2.x",
          "from": "selenium-webdriver@2.x"
        }
      }
    }
  }
}```

in my case

**Comment by bob-martin** [comment]
Turns out my issue was unique to OS X 10.10 Xcode.  The proper links for -lgcc_s.10.5 are not present.
Fixed by:
$ cd /usr/local/lib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.5.dylib
$ sudo ln -s ../../lib/libSystem.B.dylib libgcc_s.10.4.dylib

**Comment by mickey9801** [comment]
I have a similar issue when installing minigun with dependency with bufferutil, but bob's solution seems can't help.

**Comment by BurningDog** [comment]
Thanks @bob-martin that worked for me too. I'm on 10.10.5 running XCode 6.4

**Comment by RameshJhajharia** [comment]
Facing same issue with OS X 10.10.5 and node 4.1

ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/bufferutil.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/bufferutil
gyp ERR! node -v v4.1.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "bufferutil"
npm ERR! node v4.1.0
npm ERR! npm  v3.3.3
npm ERR! code ELIFECYCLE

npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

**Comment by RameshJhajharia** [comment]
Thanks @bob-martin  this worked for me too.

**Comment by 3rd-Eden** [comment]
This should probably be reported at Node gyp as that generates the build files.

**Comment by kbowerma** [comment]
my buddy and I just both blew away node and rebuilt it and are getting the same error as @RameshJhajharia except our error says 

```
npm ERR! Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
```
which states the propblem is with 1.1.0 not 1.2.1.    The node/npm version is
v4.1.1 / 3.3.4

we tried using bobs symlink trick but it did not work for us

**Comment by juliemr** [comment]
See also the issue for node-gyp: https://github.com/nodejs/node-gyp/issues/734

**Comment by hedleygois** [comment]
@bob-martin solution works pretty well for me
tks!

**Comment by edwios** [comment]
@bob-martin solution works beautifully here, too. Big thanks!!!

**Comment by sergeylukin** [comment]
Thanks @bob-martin that worked for me too!

**Comment by 3rd-Eden** [comment]
As this something that is outside our control, should be solved by your os, installation, or even `node-gyp` so I'm going to close this issue.

**Comment by lulu44600** [comment]
@bob-martin You made my day !!

**Comment by qjlee** [comment]
@bob-martin thanks a lot, it saved me at least a few hours.

**Comment by thuongvu** [comment]
@bob-martin thank you!

**Comment by athaax** [comment]
@bob-martin I'm getting the same issue, running the latest versions of npm and node, except I'm on windows.

**Comment by patnaikshekhar** [comment]
Thanks @bob-martin your fix works.

**Comment by davidspiess** [comment]
Same problem as @athaax on windows

**Comment by riapp** [comment]
Windows 8.1
Node 5.1.0
```
d:\Projects\2015\Clientbro.WebApp>npm rb

> bufferutil@1.2.1 install d:\Projects\node_modules\buffer
util
> node-gyp rebuild
d:\Projects\node_modules\bufferutil>if not defined npm_con
fig_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! clean error
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'd:\Projects\2015\C
lientbro.WebApp\node_modules\bufferutil\build\Release\bufferutil.node'
gyp ERR! stack     at Error (native)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\Projects\node_modules\bufferutil
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "rb"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\Projects\npm-debug.log
```

**Comment by bosco2010** [comment]
Thanks @bob-martin!  Your fix worked for me as well.

**Comment by mihaigiurgeanu** [comment]
I tried the fix described by @bob-martin, but it didn't work for me. I have OSX 10.11.1 with Xcode 7 installed.

**Comment by Taakn** [comment]
I have Xcode 7.2.1 and OSX 10.11.12 and the fix does not work for me either unfortunately.

**Comment by bg5hfc** [comment]
I'm using OSX10.11.3 and Xcode 7.2.1, @bob-martin 's fix doesn't work either.

**Comment by selvan** [comment]
Had same issue with XCode 7.3.1 (7D1014), updating "Command Line Tools" to latest from (https://developer.apple.com/downloads/) and restarting machine did fix the issue. Credit: https://github.com/nodejs/node/issues/4094

**Comment by nathguen** [comment]
I have OSX10.11.6 and XCode 7.3.1. My fix was reverting from `node@10` to node@8`.

**Comment by andrewleo** [comment]
YES! downgrade node@10 to 8 solved the problems.
Thanks guys :)
