### ISSUE TITLE
Why do I need Python?

### ISSUE THREAD

**Issue by glen-84** [websockets/bufferutil#19]
I get the following output when installing (from browser-sync I guess):

    $ npm install
    npm WARN install Couldn't install optional dependency: Unsupported
    npm WARN prefer global node-gyp@3.0.3 should be installed with -g

    > bufferutil@1.2.1 install D:\Programming\Git\github\x\node_modules\bufferutil
    > node-gyp rebuild

    D:\Programming\Git\github\x\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd D:\Programming\Git\github\x\node_modules\bufferutil
    gyp ERR! node -v v4.1.0
    gyp ERR! node-gyp -v v3.0.1
    gyp ERR! not ok
    npm WARN install:bufferutil bufferutil@1.2.1 install: `node-gyp rebuild`
    npm WARN install:bufferutil Exit status 1

    > utf-8-validate@1.2.1 install D:\Programming\Git\github\x\node_modules\utf-8-validate
    > node-gyp rebuild

    D:\Programming\Git\github\x\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
    gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd D:\Programming\Git\github\x\node_modules\utf-8-validate
    gyp ERR! node -v v4.1.0
    gyp ERR! node-gyp -v v3.0.1
    gyp ERR! not ok
    npm WARN install:utf-8-validate utf-8-validate@1.2.1 install: `node-gyp rebuild`
    npm WARN install:utf-8-validate Exit status 1

    > node-sass@3.3.3 install D:\Programming\Git\github\x\node_modules\node-sass
    > node scripts/install.js

    Binary downloaded and installed at D:\Programming\Git\github\x\node_modules\node-sass\vendor\win32-x64-46\binding.node

    > spawn-sync@1.0.13 postinstall D:\Programming\Git\github\x\node_modules\spawn-sync
    > node postinstall

    > node-sass@3.3.3 postinstall D:\Programming\Git\github\x\node_modules\node-sass
    > node scripts/build.js

    ` D:\Programming\Git\github\x\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
     testing binary.
    Binary is fine; exiting.
    npm WARN prefer global node-gyp@3.0.3 should be installed with -g

    > node-sass@3.3.3 install D:\Programming\Git\github\x\node_modules\node-sass
    > node scripts/install.js

    > node-sass@3.3.3 postinstall D:\Programming\Git\github\x\node_modules\node-sass
    > node scripts/build.js

    ` D:\Programming\Git\github\x\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
     testing binary.
    Binary is fine; exiting.

    > spawn-sync@1.0.13 postinstall D:\Programming\Git\github\x\node_modules\spawn-sync
    > node postinstall

Do I really have to install Python, or is this a bug?

**Comment by 3rd-Eden** [comment]
You need python as thats part of node's binary compilation. The folks who build and bundled `node-gyp` with node might know why it's a required and not bundled and installed when node is installed.

**Comment by glen-84** [comment]
I'm trying to understand what exactly needs to be compiled, and why. All I'm doing is installing a few packages like gulp-sass and browser-sync.
