### ISSUE TITLE
latest npm, python 2.7.x, not installing

### ISSUE THREAD

**Issue by robertbaker** [websockets/bufferutil#2]
219 verbose stack Error: bufferutil@1.0.1 install: `node-gyp rebuild`
219 verbose stack Exit status 1
219 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
219 verbose stack     at EventEmitter.emit (events.js:110:17)
219 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
219 verbose stack     at ChildProcess.emit (events.js:110:17)
219 verbose stack     at maybeClose (child_process.js:1008:16)
219 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
220 verbose pkgid bufferutil@1.0.1
221 verbose cwd D:\CodeRoot\OpSuite\OpSuite\OpSuiteDev\Website\OpSuite.MobilePOS
222 error Windows_NT 6.1.7601
223 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "bufferutil"
224 error node v0.12.0
225 error npm  v2.7.3
226 error code ELIFECYCLE
227 error bufferutil@1.0.1 install: `node-gyp rebuild`
227 error Exit status 1
228 error Failed at the bufferutil@1.0.1 install script 'node-gyp rebuild'.
228 error This is most likely a problem with the bufferutil package,
228 error not with npm itself.
228 error Tell the author that this fails on your system:
228 error     node-gyp rebuild
228 error You can get their info via:
228 error     npm owner ls bufferutil
228 error There is likely additional logging output above.
229 verbose exit [ 1, true ]
230 verbose unbuild node_modules\bufferutil
231 info preuninstall bufferutil@1.0.1
232 info uninstall bufferutil@1.0.1

**Comment by felicienfrancois** [comment]
I got the same issue (iojs 1.6.2, npm 2.7.1, python 2.7.9)
```
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1044:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "c:\\Program Files\\iojs\\node.exe" "c:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Felicien\git\TweakStyle\target\dev\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v1.6.2
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```

**Comment by robertbaker** [comment]
I ended up re-installing the latested node. fixed my problem.

**Comment by DominikDitoIvosevic** [comment]
Reinstalling node also fixed this for me although I did have a pretty fresh install of node. Windows 8.1
