### ISSUE TITLE
Cannot install on Win7 (x64) with VS 2013 installed

### ISSUE THREAD

**Issue by m-baumgartner** [websockets/bufferutil#23]
When installing [aglio](https://github.com/danielgtaylor/aglio) it fails when it comes to compile `bufferutil` on my station.

I have

* Windows 7 Pro 64bits.
* Visual Studio community 2013
* npm v3.2.2 (upgrading helped me solve [this](https://github.com/apiaryio/protagonist/issues/97) )

Here follows my npm-debug.log

> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '--msvs-version=2013',
1 verbose cli   'bufferutil' ]
2 info using npm@3.2.2
3 info using node@v4.2.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData bufferutil
8 silly fetchNamedPackageData bufferutil
9 silly mapToRegistry name bufferutil
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/bufferutil
13 verbose request uri https://registry.npmjs.org/bufferutil
14 verbose request no auth needed
15 info attempt registry request try #1 at 17:38:48
16 verbose request id c9de00c02955ca62
17 verbose etag "5YYVHBVQTZVEKNM2IBRTU84J5"
18 http request GET https://registry.npmjs.org/bufferutil
19 http 304 https://registry.npmjs.org/bufferutil
20 silly get cb [ 304,
20 silly get   { date: 'Wed, 14 Oct 2015 15:38:49 GMT',
20 silly get     via: '1.1 varnish',
20 silly get     'cache-control': 'max-age=60',
20 silly get     etag: '"5YYVHBVQTZVEKNM2IBRTU84J5"',
20 silly get     age: '3',
20 silly get     connection: 'keep-alive',
20 silly get     'x-served-by': 'cache-fra1246-FRA',
20 silly get     'x-cache': 'HIT',
20 silly get     'x-cache-hits': '1',
20 silly get     'x-timer': 'S1444837129.409135,VS0,VE0',
20 silly get     vary: 'Accept' } ]
21 verbose etag https://registry.npmjs.org/bufferutil from cache
22 verbose get saving bufferutil to C:\Users\Dev\AppData\Roaming\npm-cache\registry.npmjs.org\bufferutil\.cache.json
23 silly install normalizeTree
24 silly loadCurrentTree Finishing
25 silly loadIdealTree Starting
26 silly install loadIdealTree
27 silly cloneCurrentTree Starting
28 silly install cloneCurrentTreeToIdealTree
29 silly cloneCurrentTree Finishing
30 silly loadShrinkwrap Starting
31 silly install loadShrinkwrap
32 silly loadShrinkwrap Finishing
33 silly loadAllDepsIntoIdealTree Starting
34 silly install loadAllDepsIntoIdealTree
35 silly resolveWithNewModule bufferutil@1.2.1 checking installable status
36 silly cache add args [ 'bufferutil', null ]
37 verbose cache add spec bufferutil
38 silly cache add parsed spec Result {
38 silly cache add   raw: 'bufferutil',
38 silly cache add   scope: null,
38 silly cache add   name: 'bufferutil',
38 silly cache add   rawSpec: '',
38 silly cache add   spec: '*',
38 silly cache add   type: 'range' }
39 silly addNamed bufferutil@*
40 verbose addNamed "*" is a valid semver range for bufferutil
41 silly addNameRange { name: 'bufferutil', range: '*', hasData: false }
42 silly mapToRegistry name bufferutil
43 silly mapToRegistry using default registry
44 silly mapToRegistry registry https://registry.npmjs.org/
45 silly mapToRegistry uri https://registry.npmjs.org/bufferutil
46 verbose addNameRange registry:https://registry.npmjs.org/bufferutil not in flight; fetching
47 verbose get https://registry.npmjs.org/bufferutil not expired, no request
48 silly addNameRange number 2 { name: 'bufferutil', range: '*', hasData: true }
49 silly addNameRange versions [ 'bufferutil',
49 silly addNameRange   [ '1.0.0', '1.0.1', '1.1.0', '1.2.0', '1.2.1' ] ]
50 silly addNamed bufferutil@1.2.1
51 verbose addNamed "1.2.1" is a plain semver version for bufferutil
52 silly cache afterAdd bufferutil@1.2.1
53 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\bufferutil\1.2.1\package\package.json not in flight; writing
54 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\bufferutil\1.2.1\package\package.json written
55 silly fetchNamedPackageData bindings
56 silly mapToRegistry name bindings
57 silly mapToRegistry using default registry
58 silly mapToRegistry registry https://registry.npmjs.org/
59 silly mapToRegistry uri https://registry.npmjs.org/bindings
60 silly fetchNamedPackageData nan
61 silly mapToRegistry name nan
62 silly mapToRegistry using default registry
63 silly mapToRegistry registry https://registry.npmjs.org/
64 silly mapToRegistry uri https://registry.npmjs.org/nan
65 verbose request uri https://registry.npmjs.org/bindings
66 verbose request no auth needed
67 info attempt registry request try #1 at 17:38:49
68 verbose etag "547Q3C60W4DUGPOZ65YOO6930"
69 http request GET https://registry.npmjs.org/bindings
70 verbose request uri https://registry.npmjs.org/nan
71 verbose request no auth needed
72 info attempt registry request try #1 at 17:38:49
73 verbose etag "EEJEYBDBWDA07LWTXUI68JUWL"
74 http request GET https://registry.npmjs.org/nan
75 http 304 https://registry.npmjs.org/bindings
76 silly get cb [ 304,
76 silly get   { date: 'Wed, 14 Oct 2015 15:38:49 GMT',
76 silly get     via: '1.1 varnish',
76 silly get     'cache-control': 'max-age=60',
76 silly get     etag: '"547Q3C60W4DUGPOZ65YOO6930"',
76 silly get     age: '53',
76 silly get     connection: 'keep-alive',
76 silly get     'x-served-by': 'cache-fra1230-FRA',
76 silly get     'x-cache': 'HIT',
76 silly get     'x-cache-hits': '4',
76 silly get     'x-timer': 'S1444837129.674503,VS0,VE0',
76 silly get     vary: 'Accept' } ]
77 verbose etag https://registry.npmjs.org/bindings from cache
78 verbose get saving bindings to C:\Users\Dev\AppData\Roaming\npm-cache\registry.npmjs.org\bindings\.cache.json
79 http 304 https://registry.npmjs.org/nan
80 silly get cb [ 304,
80 silly get   { date: 'Wed, 14 Oct 2015 15:38:49 GMT',
80 silly get     via: '1.1 varnish',
80 silly get     'cache-control': 'max-age=60',
80 silly get     etag: '"EEJEYBDBWDA07LWTXUI68JUWL"',
80 silly get     age: '20',
80 silly get     connection: 'keep-alive',
80 silly get     'x-served-by': 'cache-fra1233-FRA',
80 silly get     'x-cache': 'HIT',
80 silly get     'x-cache-hits': '3',
80 silly get     'x-timer': 'S1444837129.684786,VS0,VE0',
80 silly get     vary: 'Accept' } ]
81 verbose etag https://registry.npmjs.org/nan from cache
82 verbose get saving nan to C:\Users\Dev\AppData\Roaming\npm-cache\registry.npmjs.org\nan\.cache.json
83 silly resolveWithNewModule bindings@1.2.1 checking installable status
84 silly cache add args [ 'bindings@1.2.x', null ]
85 verbose cache add spec bindings@1.2.x
86 silly cache add parsed spec Result {
86 silly cache add   raw: 'bindings@1.2.x',
86 silly cache add   scope: null,
86 silly cache add   name: 'bindings',
86 silly cache add   rawSpec: '1.2.x',
86 silly cache add   spec: '>=1.2.0 <1.3.0',
86 silly cache add   type: 'range' }
87 silly addNamed bindings@>=1.2.0 <1.3.0
88 verbose addNamed ">=1.2.0 <1.3.0" is a valid semver range for bindings
89 silly addNameRange { name: 'bindings', range: '>=1.2.0 <1.3.0', hasData: false }
90 silly mapToRegistry name bindings
91 silly mapToRegistry using default registry
92 silly mapToRegistry registry https://registry.npmjs.org/
93 silly mapToRegistry uri https://registry.npmjs.org/bindings
94 verbose addNameRange registry:https://registry.npmjs.org/bindings not in flight; fetching
95 silly resolveWithNewModule nan@2.1.0 checking installable status
96 silly cache add args [ 'nan@^2.0.5', null ]
97 verbose cache add spec nan@^2.0.5
98 silly cache add parsed spec Result {
98 silly cache add   raw: 'nan@^2.0.5',
98 silly cache add   scope: null,
98 silly cache add   name: 'nan',
98 silly cache add   rawSpec: '^2.0.5',
98 silly cache add   spec: '>=2.0.5 <3.0.0',
98 silly cache add   type: 'range' }
99 silly addNamed nan@>=2.0.5 <3.0.0
100 verbose addNamed ">=2.0.5 <3.0.0" is a valid semver range for nan
101 silly addNameRange { name: 'nan', range: '>=2.0.5 <3.0.0', hasData: false }
102 silly mapToRegistry name nan
103 silly mapToRegistry using default registry
104 silly mapToRegistry registry https://registry.npmjs.org/
105 silly mapToRegistry uri https://registry.npmjs.org/nan
106 verbose addNameRange registry:https://registry.npmjs.org/nan not in flight; fetching
107 verbose get https://registry.npmjs.org/bindings not expired, no request
108 silly addNameRange number 2 { name: 'bindings', range: '>=1.2.0 <1.3.0', hasData: true }
109 silly addNameRange versions [ 'bindings',
109 silly addNameRange   [ '0.0.1',
109 silly addNameRange     '0.1.0',
109 silly addNameRange     '0.1.1',
109 silly addNameRange     '0.2.0',
109 silly addNameRange     '0.2.1',
109 silly addNameRange     '0.2.2',
109 silly addNameRange     '0.2.3',
109 silly addNameRange     '0.2.4',
109 silly addNameRange     '0.3.0',
109 silly addNameRange     '0.4.0',
109 silly addNameRange     '1.0.0',
109 silly addNameRange     '1.1.0',
109 silly addNameRange     '1.1.1',
109 silly addNameRange     '1.2.0',
109 silly addNameRange     '1.2.1' ] ]
110 silly addNamed bindings@1.2.1
111 verbose addNamed "1.2.1" is a plain semver version for bindings
112 verbose get https://registry.npmjs.org/nan not expired, no request
113 silly addNameRange number 2 { name: 'nan', range: '>=2.0.5 <3.0.0', hasData: true }
114 silly addNameRange versions [ 'nan',
114 silly addNameRange   [ '0.3.0-wip',
114 silly addNameRange     '0.3.0-wip2',
114 silly addNameRange     '0.3.0',
114 silly addNameRange     '0.3.1',
114 silly addNameRange     '0.3.2',
114 silly addNameRange     '0.4.0',
114 silly addNameRange     '0.4.1',
114 silly addNameRange     '0.4.2',
114 silly addNameRange     '0.4.3',
114 silly addNameRange     '0.4.4',
114 silly addNameRange     '0.5.0',
114 silly addNameRange     '0.5.1',
114 silly addNameRange     '0.5.2',
114 silly addNameRange     '0.6.0',
114 silly addNameRange     '0.7.0',
114 silly addNameRange     '0.7.1',
114 silly addNameRange     '0.8.0',
114 silly addNameRange     '1.0.0',
114 silly addNameRange     '1.1.0',
114 silly addNameRange     '1.1.1',
114 silly addNameRange     '1.1.2',
114 silly addNameRange     '1.2.0',
114 silly addNameRange     '1.3.0',
114 silly addNameRange     '1.4.0',
114 silly addNameRange     '1.4.1',
114 silly addNameRange     '1.5.0',
114 silly addNameRange     '1.4.2',
114 silly addNameRange     '1.4.3',
114 silly addNameRange     '1.5.1',
114 silly addNameRange     '1.5.2',
114 silly addNameRange     '1.6.0',
114 silly addNameRange     '1.5.3',
114 silly addNameRange     '1.6.1',
114 silly addNameRange     '1.6.2',
114 silly addNameRange     '1.7.0',
114 silly addNameRange     '1.8.0',
114 silly addNameRange     '1.8.1',
114 silly addNameRange     '1.8.2',
114 silly addNameRange     '1.8.3',
114 silly addNameRange     '1.8.4',
114 silly addNameRange     '1.9.0',
114 silly addNameRange     '2.0.0',
114 silly addNameRange     '2.0.1',
114 silly addNameRange     '2.0.2',
114 silly addNameRange     '2.0.3',
114 silly addNameRange     '2.0.4',
114 silly addNameRange     '2.0.5',
114 silly addNameRange     '2.0.6',
114 silly addNameRange     '2.0.7',
114 silly addNameRange     '2.0.8',
114 silly addNameRange     '2.0.9',
114 silly addNameRange     '2.1.0' ] ]
115 silly addNamed nan@2.1.0
116 verbose addNamed "2.1.0" is a plain semver version for nan
117 silly cache afterAdd bindings@1.2.1
118 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json not in flight; writing
119 silly cache afterAdd nan@2.1.0
120 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\nan\2.1.0\package\package.json not in flight; writing
121 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\bindings\1.2.1\package\package.json written
122 verbose afterAdd C:\Users\Dev\AppData\Roaming\npm-cache\nan\2.1.0\package\package.json written
123 silly loadAllDepsIntoIdealTree Finishing
124 silly idealTree:prePrune C:\Users\Dev\AppData\Roaming\npm
124 silly idealTree:prePrune └─┬ bufferutil@1.2.1
124 silly idealTree:prePrune   ├── bindings@1.2.1
124 silly idealTree:prePrune   └── nan@2.1.0
125 silly loadIdealTree Finishing
126 silly currentTree C:\Users\Dev\AppData\Roaming\npm
127 silly idealTree C:\Users\Dev\AppData\Roaming\npm
127 silly idealTree └─┬ bufferutil@1.2.1
127 silly idealTree   ├── bindings@1.2.1
127 silly idealTree   └── nan@2.1.0
128 silly generateActionsToTake Starting
129 silly install generateActionsToTake
130 silly generateActionsToTake Finishing
131 silly diffTrees action count 3
132 silly diffTrees add bindings@1.2.1
133 silly diffTrees add nan@2.1.0
134 silly diffTrees add bufferutil@1.2.1
135 silly decomposeActions action count 24
136 silly decomposeActions fetch bindings@1.2.1
137 silly decomposeActions extract bindings@1.2.1
138 silly decomposeActions preinstall bindings@1.2.1
139 silly decomposeActions build bindings@1.2.1
140 silly decomposeActions install bindings@1.2.1
141 silly decomposeActions postinstall bindings@1.2.1
142 silly decomposeActions test bindings@1.2.1
143 silly decomposeActions finalize bindings@1.2.1
144 silly decomposeActions fetch nan@2.1.0
145 silly decomposeActions extract nan@2.1.0
146 silly decomposeActions preinstall nan@2.1.0
147 silly decomposeActions build nan@2.1.0
148 silly decomposeActions install nan@2.1.0
149 silly decomposeActions postinstall nan@2.1.0
150 silly decomposeActions test nan@2.1.0
151 silly decomposeActions finalize nan@2.1.0
152 silly decomposeActions fetch bufferutil@1.2.1
153 silly decomposeActions extract bufferutil@1.2.1
154 silly decomposeActions preinstall bufferutil@1.2.1
155 silly decomposeActions build bufferutil@1.2.1
156 silly decomposeActions install bufferutil@1.2.1
157 silly decomposeActions postinstall bufferutil@1.2.1
158 silly decomposeActions test bufferutil@1.2.1
159 silly decomposeActions finalize bufferutil@1.2.1
160 silly executeActions Starting
161 silly install executeActions
162 silly doSerial global-install 0
163 silly doParallel fetch 3
164 verbose lock using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\staging-707a5ac61b752719.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging
165 silly doParallel extract 3
166 silly extract bindings
167 silly extract nan
168 silly extract bufferutil
169 verbose unbuild node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272
170 verbose unbuild node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781
171 verbose unbuild node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f
172 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272 is being purged from base C:\Users\Dev\AppData\Roaming\npm
173 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272
174 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781 is being purged from base C:\Users\Dev\AppData\Roaming\npm
175 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781
176 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f is being purged from base C:\Users\Dev\AppData\Roaming\npm
177 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f
178 verbose tar unpack C:\Users\Dev\AppData\Roaming\npm-cache\bindings\1.2.1\package.tgz
179 verbose tar unpacking to C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272
180 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272 is being purged
181 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272
182 verbose tar unpack C:\Users\Dev\AppData\Roaming\npm-cache\bufferutil\1.2.1\package.tgz
183 verbose tar unpacking to C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781
184 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781 is being purged
185 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781
186 verbose tar unpack C:\Users\Dev\AppData\Roaming\npm-cache\nan\2.1.0\package.tgz
187 verbose tar unpacking to C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f
188 silly gentlyRm C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f is being purged
189 verbose gentlyRm don't care about contents; nuking C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f
190 silly gunzTarPerm modes [ '777', '666' ]
191 silly gunzTarPerm modes [ '777', '666' ]
192 silly gunzTarPerm modes [ '777', '666' ]
193 silly gunzTarPerm extractEntry package.json
194 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
195 silly gunzTarPerm extractEntry package.json
196 silly gunzTarPerm modified mode [ 'package.json', 420, 438 ]
197 silly gunzTarPerm extractEntry package.json
198 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
199 silly gunzTarPerm extractEntry README.md
200 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
201 silly gunzTarPerm extractEntry bindings.js
202 silly gunzTarPerm modified mode [ 'bindings.js', 420, 438 ]
203 silly gunzTarPerm extractEntry .npmignore
204 silly gunzTarPerm modified mode [ '.npmignore', 420, 438 ]
205 silly gunzTarPerm extractEntry README.md
206 silly gunzTarPerm modified mode [ 'README.md', 420, 438 ]
207 silly gunzTarPerm extractEntry README.md
208 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
209 silly gunzTarPerm extractEntry include_dirs.js
210 silly gunzTarPerm modified mode [ 'include_dirs.js', 436, 438 ]
211 silly gunzTarPerm extractEntry fallback.js
212 silly gunzTarPerm modified mode [ 'fallback.js', 420, 438 ]
213 silly gunzTarPerm extractEntry index.js
214 silly gunzTarPerm modified mode [ 'index.js', 420, 438 ]
215 silly gunzTarPerm extractEntry nan_converters.h
216 silly gunzTarPerm modified mode [ 'nan_converters.h', 436, 438 ]
217 silly gunzTarPerm extractEntry LICENSE.md
218 silly gunzTarPerm modified mode [ 'LICENSE.md', 436, 438 ]
219 silly gunzTarPerm extractEntry .dntrc
220 silly gunzTarPerm modified mode [ '.dntrc', 436, 438 ]
221 silly gunzTarPerm extractEntry appveyor.yml
222 silly gunzTarPerm modified mode [ 'appveyor.yml', 436, 438 ]
223 silly gunzTarPerm extractEntry .travis.yml
224 silly gunzTarPerm modified mode [ '.travis.yml', 420, 438 ]
225 silly gunzTarPerm extractEntry binding.gyp
226 silly gunzTarPerm modified mode [ 'binding.gyp', 420, 438 ]
227 silly gunzTarPerm extractEntry doc/new.md
228 silly gunzTarPerm modified mode [ 'doc/new.md', 436, 438 ]
229 silly gunzTarPerm extractEntry doc/.build.sh
230 silly gunzTarPerm modified mode [ 'doc/.build.sh', 509, 511 ]
231 silly gunzTarPerm extractEntry src/bufferutil.cc
232 silly gunzTarPerm modified mode [ 'src/bufferutil.cc', 420, 438 ]
233 silly gunzTarPerm extractEntry doc/buffers.md
234 silly gunzTarPerm modified mode [ 'doc/buffers.md', 436, 438 ]
235 silly gunzTarPerm extractEntry doc/callback.md
236 silly gunzTarPerm modified mode [ 'doc/callback.md', 436, 438 ]
237 silly gunzTarPerm extractEntry doc/converters.md
238 silly gunzTarPerm modified mode [ 'doc/converters.md', 436, 438 ]
239 silly gunzTarPerm extractEntry doc/errors.md
240 silly gunzTarPerm modified mode [ 'doc/errors.md', 436, 438 ]
241 silly gunzTarPerm extractEntry doc/maybe_types.md
242 silly gunzTarPerm modified mode [ 'doc/maybe_types.md', 436, 438 ]
243 silly gunzTarPerm extractEntry doc/methods.md
244 silly gunzTarPerm modified mode [ 'doc/methods.md', 436, 438 ]
245 silly gunzTarPerm extractEntry doc/asyncworker.md
246 silly gunzTarPerm modified mode [ 'doc/asyncworker.md', 436, 438 ]
247 silly gunzTarPerm extractEntry doc/node_misc.md
248 silly gunzTarPerm modified mode [ 'doc/node_misc.md', 436, 438 ]
249 silly gunzTarPerm extractEntry doc/persistent.md
250 silly gunzTarPerm modified mode [ 'doc/persistent.md', 436, 438 ]
251 silly gunzTarPerm extractEntry doc/scopes.md
252 silly gunzTarPerm modified mode [ 'doc/scopes.md', 436, 438 ]
253 silly gunzTarPerm extractEntry doc/script.md
254 silly gunzTarPerm modified mode [ 'doc/script.md', 436, 438 ]
255 silly gunzTarPerm extractEntry doc/string_bytes.md
256 silly gunzTarPerm modified mode [ 'doc/string_bytes.md', 436, 438 ]
257 silly gunzTarPerm extractEntry doc/v8_internals.md
258 silly gunzTarPerm modified mode [ 'doc/v8_internals.md', 436, 438 ]
259 silly gunzTarPerm extractEntry doc/v8_misc.md
260 silly gunzTarPerm modified mode [ 'doc/v8_misc.md', 436, 438 ]
261 silly gunzTarPerm extractEntry nan.h
262 silly gunzTarPerm modified mode [ 'nan.h', 436, 438 ]
263 silly gunzTarPerm extractEntry nan_callbacks.h
264 silly gunzTarPerm modified mode [ 'nan_callbacks.h', 436, 438 ]
265 silly gunzTarPerm extractEntry nan_callbacks_12_inl.h
266 silly gunzTarPerm modified mode [ 'nan_callbacks_12_inl.h', 436, 438 ]
267 silly gunzTarPerm extractEntry nan_callbacks_pre_12_inl.h
268 silly gunzTarPerm modified mode [ 'nan_callbacks_pre_12_inl.h', 436, 438 ]
269 silly gunzTarPerm extractEntry nan_converters_43_inl.h
270 silly gunzTarPerm modified mode [ 'nan_converters_43_inl.h', 436, 438 ]
271 silly gunzTarPerm extractEntry nan_converters_pre_43_inl.h
272 silly gunzTarPerm modified mode [ 'nan_converters_pre_43_inl.h', 436, 438 ]
273 silly gunzTarPerm extractEntry nan_implementation_12_inl.h
274 silly gunzTarPerm modified mode [ 'nan_implementation_12_inl.h', 436, 438 ]
275 silly gunzTarPerm extractEntry nan_implementation_pre_12_inl.h
276 silly gunzTarPerm modified mode [ 'nan_implementation_pre_12_inl.h', 436, 438 ]
277 silly gunzTarPerm extractEntry nan_maybe_43_inl.h
278 silly gunzTarPerm modified mode [ 'nan_maybe_43_inl.h', 436, 438 ]
279 silly gunzTarPerm extractEntry nan_maybe_pre_43_inl.h
280 silly gunzTarPerm modified mode [ 'nan_maybe_pre_43_inl.h', 436, 438 ]
281 silly gunzTarPerm extractEntry nan_new.h
282 silly gunzTarPerm modified mode [ 'nan_new.h', 436, 438 ]
283 silly gunzTarPerm extractEntry nan_object_wrap.h
284 silly gunzTarPerm modified mode [ 'nan_object_wrap.h', 436, 438 ]
285 silly gunzTarPerm extractEntry nan_persistent_12_inl.h
286 silly gunzTarPerm modified mode [ 'nan_persistent_12_inl.h', 436, 438 ]
287 silly gunzTarPerm extractEntry nan_persistent_pre_12_inl.h
288 silly gunzTarPerm modified mode [ 'nan_persistent_pre_12_inl.h', 436, 438 ]
289 silly gunzTarPerm extractEntry nan_string_bytes.h
290 silly gunzTarPerm modified mode [ 'nan_string_bytes.h', 436, 438 ]
291 silly gunzTarPerm extractEntry nan_typedarray_contents.h
292 silly gunzTarPerm modified mode [ 'nan_typedarray_contents.h', 436, 438 ]
293 silly gunzTarPerm extractEntry nan_weak.h
294 silly gunzTarPerm modified mode [ 'nan_weak.h', 436, 438 ]
295 silly gunzTarPerm extractEntry CHANGELOG.md
296 silly gunzTarPerm modified mode [ 'CHANGELOG.md', 436, 438 ]
297 silly gunzTarPerm extractEntry tools/package.json
298 silly gunzTarPerm modified mode [ 'tools/package.json', 436, 438 ]
299 silly gunzTarPerm extractEntry tools/README.md
300 silly gunzTarPerm modified mode [ 'tools/README.md', 436, 438 ]
301 silly gunzTarPerm extractEntry tools/1to2.js
302 silly gunzTarPerm modified mode [ 'tools/1to2.js', 509, 511 ]
303 silly doParallel preinstall 3
304 silly preinstall bindings C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272
305 info preinstall bindings@1.2.1
306 silly preinstall nan C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f
307 info preinstall nan@2.1.0
308 silly preinstall bufferutil C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781
309 info preinstall bufferutil@1.2.1
310 silly doReverseSerial remove 0
311 silly doSerial move 0
312 silly doSerial finalize 3
313 silly finalize C:\Users\Dev\AppData\Roaming\npm\node_modules\bufferutil\node_modules\bindings
314 silly finalize C:\Users\Dev\AppData\Roaming\npm\node_modules\bufferutil\node_modules\nan
315 silly finalize C:\Users\Dev\AppData\Roaming\npm\node_modules\bufferutil
316 silly doSerial build 3
317 silly build bindings
318 info linkStuff bindings@1.2.1
319 silly linkStuff bindings@1.2.1 has C:\Users\Dev\AppData\Roaming\npm\node_modules\bufferutil\node_modules as its parent node_modules
320 silly linkStuff bindings@1.2.1 is part of a global install
321 silly linkStuff bindings@1.2.1 is installed into a global node_modules
322 verbose linkBins bindings@1.2.1
323 verbose linkMans bindings@1.2.1
324 verbose rebuildBundles bindings@1.2.1
325 silly build nan
326 info linkStuff nan@2.1.0
327 silly linkStuff nan@2.1.0 has C:\Users\Dev\AppData\Roaming\npm\node_modules\bufferutil\node_modules as its parent node_modules
328 silly linkStuff nan@2.1.0 is part of a global install
329 silly linkStuff nan@2.1.0 is installed into a global node_modules
330 verbose linkBins nan@2.1.0
331 verbose linkMans nan@2.1.0
332 verbose rebuildBundles nan@2.1.0
333 silly build bufferutil
334 info linkStuff bufferutil@1.2.1
335 silly linkStuff bufferutil@1.2.1 has C:\Users\Dev\AppData\Roaming\npm\node_modules as its parent node_modules
336 silly linkStuff bufferutil@1.2.1 is part of a global install
337 silly linkStuff bufferutil@1.2.1 is installed into a global node_modules
338 silly linkStuff bufferutil@1.2.1 is installed into the top-level global node_modules
339 verbose linkBins bufferutil@1.2.1
340 verbose linkMans bufferutil@1.2.1
341 verbose rebuildBundles bufferutil@1.2.1
342 verbose rebuildBundles [ 'bindings', 'nan' ]
343 silly doSerial global-link 0
344 silly doParallel update-linked 0
345 silly doSerial install 3
346 silly install bindings C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bindings-58b97b79f49432a2d3cbbbb476024272
347 info install bindings@1.2.1
348 silly install nan C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\nan-59b7092673b7e399ccf6f0ac5984934f
349 info install nan@2.1.0
350 silly install bufferutil C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging\bufferutil-ee7bc33bb8a28721bf9074127ef02781
351 info install bufferutil@1.2.1
352 verbose unsafe-perm in lifecycle true
353 info bufferutil@1.2.1 Failed to exec install script
354 verbose unlock done using C:\Users\Dev\AppData\Roaming\npm-cache\_locks\staging-707a5ac61b752719.lock for C:\Users\Dev\AppData\Roaming\npm\node_modules\.staging
355 silly rollbackFailedOptional Starting
356 silly rollbackFailedOptional Finishing
357 silly runTopLevelLifecycles Starting
358 silly runTopLevelLifecycles Finishing
359 silly install printInstalled
360 verbose stack Error: bufferutil@1.2.1 install: `node-gyp rebuild`
360 verbose stack Exit status 1
360 verbose stack     at EventEmitter.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:223:16)
360 verbose stack     at emitTwo (events.js:87:13)
360 verbose stack     at EventEmitter.emit (events.js:172:7)
360 verbose stack     at ChildProcess.<anonymous> (C:\Users\Dev\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:24:14)
360 verbose stack     at emitTwo (events.js:87:13)
360 verbose stack     at ChildProcess.emit (events.js:172:7)
360 verbose stack     at maybeClose (internal/child_process.js:818:16)
360 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
361 verbose pkgid bufferutil@1.2.1
362 verbose cwd C:\Program Files\nodejs
363 error Windows_NT 6.1.7601
364 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--msvs-version=2013" "bufferutil"
365 error node v4.2.1
366 error npm  v3.2.2
367 error code ELIFECYCLE
368 error bufferutil@1.2.1 install: `node-gyp rebuild`
368 error Exit status 1
369 error Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
369 error This is most likely a problem with the bufferutil package,
369 error not with npm itself.
369 error Tell the author that this fails on your system:
369 error     node-gyp rebuild
369 error You can get their info via:
369 error     npm owner ls bufferutil
369 error There is likely additional logging output above.
370 verbose exit [ 1, true ]

**Comment by sheerun** [comment]
@m-baumgartner What's the resolution?
