### ISSUE TITLE
EPROTO error when installing

### ISSUE THREAD

**Issue by papa-gene** [websockets/bufferutil#28]
Hi all!

I am facing a weird issue when trying to install the bufferutil package by using "npm install bufferutil". The installation fails and throws this error:

> npm install bufferutil
> 
> > bufferutil@1.2.1 install /data/gitlab-runner/builds/76ca499f/0/dev/node_modules/bufferutil
> > node-gyp rebuild
> 
> gyp WARN install got an error, rolling back install
> gyp ERR! configure error
> gyp ERR! stack Error: write EPROTO
> gyp ERR! stack     at Object.exports._errnoException (util.js:837:11)
> gyp ERR! stack     at exports._exceptionWithHostPort (util.js:860:20)
> gyp ERR! stack     at WriteWrap.afterWrite (net.js:760:14)
> gyp ERR! System Linux 3.13.0-66-generic
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node->gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /data/gitlab-runner/builds/76ca499f/0/dev/node_modules/bufferutil
> gyp ERR! node -v v4.0.0
> gyp ERR! node-gyp -v v3.0.3
> gyp ERR! not ok
> npm ERR! Linux 3.13.0-66-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bufferutil"
> npm ERR! node v4.0.0
> npm ERR! npm  v3.3.12
> npm ERR! code ELIFECYCLE
> 
> npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the bufferutil package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls bufferutil
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /data/gitlab-runner/builds/76ca499f/0/dev/npm-debug.log

This is on an Ubuntu 14.04 server, with node 4.0 and npm 3.3.12. No amount of Google-fu has helped. I can't figure out what this EPROTO error is all about.

Any ideas? I'm happy to provide any more info as needed.

Thanks in advance!

**Comment by lpinca** [comment]
Closing as this is an external issue, see https://github.com/nodejs/node/issues/3692.
