### ISSUE TITLE
Fails at gyp-install when trying to deploy on EBS

### ISSUE THREAD

**Issue by codekitty** [websockets/bufferutil#30]
I see there are already several open tickets on this error but I need a solution that I can use while deploying my server application to EBS. Is there a workaround I can do locally before uploading the project to the EBS so that it will run there? 

```1308 error Linux 4.1.10-17.31.amzn1.x86_64
1309 error argv "/opt/elasticbeanstalk/node-install/node-v4.2.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.1-linux-x64/bin/npm" "--production" "rebuild"
1310 error node v4.2.1
1311 error npm  v2.14.7
1312 error code ELIFECYCLE
1313 error bufferutil@1.2.1 install:`node-gyp rebuild`
1313 error Exit status 1
1314 error Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
1314 error This is most likely a problem with the bufferutil package,
1314 error not with npm itself.
1314 error Tell the author that this fails on your system:
1314 error     node-gyp rebuild
1314 error You can get their info via:
1314 error     npm owner ls bufferutil

```

```

**Comment by dmastylo** [comment]
Has anyone been able to figure this out? Very frustrating.

**Comment by aidanbon** [comment]
I went into the same issue. Out of frustration, I tried downgrade the EBS platform to "64bit Amazon Linux 2015.03 v1.4.6 running Node.js", and that seems to workaround the issue.  

Screenshot showing the Configuration at the EBS Dashboard:

![screen shot 2016-09-27 at 12 20 30 pm](https://cloud.githubusercontent.com/assets/2024333/18888426/1d2eb670-84ad-11e6-8ec3-c64d365aaa89.png)

**Comment by lpinca** [comment]
Closing as there are now pre-built binaries which are downloaded and installed with npm.
Please reopen, if the problem persists.
