### ISSUE TITLE
install error : socket hang up

### ISSUE THREAD

**Issue by 109km** [websockets/bufferutil#32]
gyp WARN EACCES user "xinhengs" does not have permission to access the dev dir "/Users/xinhengs/.node-gyp/5.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/folders/tj/5dthcyf12fx2zc64_2s70kc00000gn/T/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at TLSSocket.onHangUp (_tls_wrap.js:1076:19)
gyp ERR! stack     at TLSSocket.g (events.js:260:16)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:905:12)
gyp ERR! stack     at doNTCallback2 (node.js:450:9)
gyp ERR! stack     at process._tickCallback (node.js:364:17)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xinhengs/Desktop/WebDevs/relax/node_modules/sharp/node_modules/bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/xinhengs/Desktop/WebDevs/relax/node_modules/sharp/node_modules/bufferutil/npm-debug.log

**Comment by lpinca** [comment]
Closing this as Node.js 5 is no longer supported. Please reopen if the issue persists with a recent version of Node.js.

**Comment by 109km** [comment]
OK, thanks very much !

2016-11-27 15:47 GMT+08:00 Luigi Pinca <notifications@github.com>:
