### ISSUE TITLE
Why on earth I can't install

### ISSUE THREAD

**Issue by dKab** [websockets/bufferutil#36]
> bufferutil@1.2.1 install C:\Users\Dmitry_Kabardinov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\Users\Dmitry_Kabardinov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\no
de-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
C:\Users\Dmitry_Kabardinov.node-gyp\4.0.0\include\node\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory [C:\Users\Dmitry_Kabardinov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_module
s\ws\node_modules\bufferutil\build\bufferutil.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Dmitry_Kabardinov\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok

**Comment by marcofugaro** [comment]
I can't install either, I have Node 5, please fix this @3rd-Eden

**Comment by 3rd-Eden** [comment]
Please make pull request @marcofugaro

**Comment by marcofugaro** [comment]
@3rd-Eden it's a node-gyp issue, I finally found [these instructions](https://github.com/nodejs/node-gyp#installation) and I had to downgrade Python to 2.x and install Visual Studio to make it work, which is unbelievable!

Yes I am looking into this, this repo has 7 open issues all with problems with node-gyp configuration, from what I could find it looks like in Node 4 and 5 the [node-gyp rebuild](https://github.com/nodejs/node-gyp/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+rebuild) has always issues, isn't there an alternative to node-gyp? Or oculd this be rewritten in another language? I've been [reading something](https://nodejs.org/api/addons.html), what do you suggest?

**Comment by gravitypersists** [comment]
It's a bit much to ask some random person who's build is breaking to fix the code that you wrote. 

I fixed this problem by removing all our dependencies which relied on this lib, luckily none of them were critical.

**Comment by 3rd-Eden** [comment]
@gravitypersists I didn't write it.

**Comment by gravitypersists** [comment]
Fair enough

**Comment by developeron29** [comment]
+1 Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.

**Comment by mishoo78** [comment]
hello
installing this module via npm fails on windows and node v5 and npm v3.8 if you don't have installed a c++ compiler. IMHO this issue should be addressed as is this module is quite popular(check it's npm page), and many other modules require it more or less. Errors in console a just horrible. Please, please fix this. From what i see there is one or two PRs, and the task itself does not appear to be quite so difficult.

**Comment by crazyyi** [comment]
Failed on Mac too. XCode is needed. This is driving me mad. I guess I need to use socket.io instead of ws because this gives me so much headache.

**Comment by lpinca** [comment]
@crazyyi you don't need the full Xcode. Installing only the Xcode Command Line Tools is sufficient.

**Comment by lpinca** [comment]
For those having problems installing on windows, try to use this module https://github.com/felixrieseberg/windows-build-tools which installs all the required prerequisites.
