### ISSUE TITLE
Crashes node 0.10.41 on Windows, even when wrapped in try/catch

### ISSUE THREAD

**Issue by rmg** [websockets/bufferutil#37]
It seems that there is something weird going on between bufferutil and node that results in the binary addon building "successfully", failing to load, but even though the failure is caught it still somehow corrupts the state of the process.

I discovered this when one of our projects refused to pass on CI. All the tests passed but because the process would exit with non-zero for no apparent reason, it would report as a failure. By eliminating a chunk at a time and eventually reduced it down to strong-control-channel, then ws, then bufferutil. Here is the minimum reproduction code:

```js
try {
  require('bufferutil/build/Release/bufferutil');
} catch(e) {
  console.error(e.stack);
}
```

The output on affected systems (only node 0.10 on Windows that I have seen so far):
```
Error: A dynamic link library (DLL) initialization routine failed.
D:\b88abec9\node_modules\bufferutil\build\Release\bufferutil.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (D:\b88abec9\test\test-cluster-member.js:2:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Even though the exception is being caught (and my catch is displaying the stack trace), it still exits with non-zero. More specifically:
 * exit code: `-1073741819`
 * aka  `0xc0000005`
 * aka "access violation"..

The module appears by all other accounts to have been compiled successfully:
```
> bufferutil@1.2.1 install D:\b88abec9\node_modules\bufferutil
> node-gyp rebuild


D:\b88abec9\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\node-0.10\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.c
     Creating library D:\b88abec9\node_modules\bufferutil\build\Release\bufferutil.lib and object D:\b88abec9\node_modules\bufferutil\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> D:\b88abec9\node_modules\bufferutil\build\Release\\bufferutil.node
```

/cc @sam-github

**Comment by bnoordhuis** [comment]
FWIW, I'm not able to reproduce this locally.  Do debug builds (`node-gyp --debug rebuild`) work?

**Comment by rmg** [comment]
Ah, the joys of Windows... it looks like one of them Windows CI machines we use had an `.npmrc` in the user's home overriding the config that pointed at the correct headers. Turns out it was linking against node.lib from 0.12.7 but then trying to run it against 0.10.41.

Yay! False alarm!
