### ISSUE TITLE
Error when installing bufferutil

### ISSUE THREAD

**Issue by weixingsun** [websockets/bufferutil#43]
Hi experts,

i got a problem when installing bufferutil:

os:
android 6.0
app: termux , linux 3.4.0-g1680ab8
gcc: 6.1.0
make: 4.2
node v6.2.1
npm v3.9.5
node-gyp v3.3.1

command:
npm i --save bufferutil

full log:
[npm.install.txt](https://github.com/websockets/bufferutil/files/304780/npm.install.txt)

**Comment by lpinca** [comment]
What's the GCC version?

**Comment by lpinca** [comment]
Oh nvm, 6.1.0.

**Comment by johnjarrard** [comment]
Did you resolve this issue?

**Comment by AdaRoseEdwards** [comment]
Termux is missing a few packages by default, install these:

apt install python2
apt install make
apt install clang

**Comment by lpinca** [comment]
@eriknyk that's not an error. You are installing `bufferutil@2.0.1` and there is no pre-built version for Node.js 8 so you get a warning but the module is compiled correctly.

You can update to `bufferutil@^3.0.1` which has pre-built binaries for Node.js 8.

**Comment by eriknyk** [comment]
Thank you very much @lpinca

**Comment by lpinca** [comment]
Closing, please comment if needed.
