### ISSUE TITLE
bufferutil.tlog

### ISSUE THREAD

**Issue by reedmt** [websockets/bufferutil#45]
After uninstall of bufferutil `npm uninstall --save bufferutil`,  a nested folder named /bufferutil.tlog will be recreated.  This includes the complete path it was declared under during installation.  Over time the contents of the folder will grow larger with new files.  The new files follow this format:  link-VCTIP.[read, write, delete].[0-9]+.tlog (e.g. link-VCTIP.write.24.tlog). 

How should the folder and its dependencies be removed and updated so that this does not occur?

**Comment by 3rd-Eden** [comment]
No clue, it's probably a build artifact from npm.

**Comment by lpinca** [comment]
I think those files are generated by MS build system, but I don't know if there is a way to prevent them from being created.

**Comment by lpinca** [comment]
Closing as this is an external issue.
