### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by austinkelleher** [websockets/bufferutil#46]
I am getting deprecation issues related to `v8::ObjectTemplate::Set()` using `ws` on Node 6.2.2. It looks like the issue is fixed in the latest commit (https://github.com/websockets/bufferutil/commit/18b449aff48f355005f37a59ccb4058eee01c77b), but a new version on npm has not be published. 

cc @3rd-Eden

**Comment by aldendaniels** [comment]
@3rd-Eden - Any plans for another NPM release?

**Comment by liviubunda** [comment]
+1 for the npm release

**Comment by lpinca** [comment]
1.3.0 has been release, closing.
