### ISSUE TITLE
Please support nodejs in your build script

### ISSUE THREAD

**Issue by cg-d** [websockets/bufferutil#50]
> bufferutil@1.0.1 install /usr/local/lib/node_modules/nativescript/node_modules/bufferutil
> node ./build.js

sh: 1: node: not found
/usr/local/lib
└── (empty)

npm ERR! Linux 4.7.2-040702-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nativescript"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! bufferutil@1.0.1 install: `node ./build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bufferutil@1.0.1 install script 'node ./build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bufferutil
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

One can easily fix this by installing nodejs-legacy but I'd prefer a more robust solution on your side :-)

**Comment by lpinca** [comment]
You can probably fix the issue by just creating a symbolic link:

```
sudo ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by cg-d** [comment]
Which is what installing nodejs-legacy will do.

**Comment by lpinca** [comment]
There is no `build.js` in this repo. I'm not sure where that comes from.

**Comment by lpinca** [comment]
Ok, it seems that the `nativescript` module uses this fork https://github.com/telerik/bufferutil and as expected it has a build script https://github.com/telerik/bufferutil/blob/master/build.js.

The issue should be reported there.
