### ISSUE TITLE
libstdc++ is deprecated on macOS Sierra

### ISSUE THREAD

**Issue by zzxz** [websockets/bufferutil#53]
macOS Sierra 10.2
node v6.8.0
bufferutil@1.2.1

Fresh install on macOS Sierra with Xcode installed:

```
> bufferutil@1.2.1 install
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment 
target of OS X 10.9
```

Not sure if OS X 10.11, 10.10, or 10.9 are presenting the same warning.

Did not receive errors as #49 reports.

**Comment by lpinca** [comment]
@zzxz can you try to install from gh-53 branch and see if 3495a26 fixes the issue? Thanks.
