### ISSUE TITLE
Publish a new version for Node 10

### ISSUE THREAD

**Issue by targos** [websockets/bufferutil#95]
[NAN 2.8.0](https://github.com/nodejs/nan/blob/77d0046d4a8378a0cd31d8110130471b44c99d8d/CHANGELOG.md#280-nov-15-2017) made a fix to stop using V8's `ForceSet` API which has been removed.
The master branch here is already at NAN 2.10.0. Is it possible to publish a new version? This should fix the package and its dependents for Node 10.

**Comment by lpinca** [comment]
Will do later today.

**Comment by lpinca** [comment]
Released 3.0.4 with nan@2.10.0
